### ISSUE TITLE
problem with hash computation

### ISSUE THREAD

**Issue by mjpost** [duolingo/duolingo-sharedtask-2020#3]
Line 214470 of `train.en_hu.2020-01-13.gold.txt` is:

    prompt_bd3ef4c328484bd5bc894d6e9b1cdb72|may i see  him?

The hash is computed over the double-spaced version of this sentence, which makes downstream scoring scripts difficult, since most tools (e.g., fairseq) normalize the double-space.

Also, the hash for line 186578 seems to be incorrect:

    prompt_7c29f2cc0ce02e3031c1919bed25f4ac|the moon is in the sky.

When I compute the hash for this sentence using your code, I get

    prompt_7c29f2cc0ce02e3031c1919bed25f4ac|the moon is in the sky.

I haven't checked other languages.

**Comment by mjpost** [comment]
Similar for vi:

You have:

    prompt_5c4e78fa909249040cb2a024d52cc01f|i said yes to myself.

but I get:

    prompt_f32f27154a3b091d7e7aef44b277c7f6|i said yes to myself.

**Comment by mjpost** [comment]
And for ko:

You have:

    prompt_7c29f2cc0ce02e3031c1919bed25f4ac|the moon is in the sky.

and I get

    prompt_941700f3ff4489dd5507c658bc56e585|the moon is in the sky.

Korean also has a double-space issue:

    prompt_a715f653049e53a0af34d1037b1edaeb|i feel  responsible.

**Comment by mjpost** [comment]
CC: @mayhewsw

**Comment by mayhewsw** [comment]
ahh, good catch. You're right that the issue has to do with spaces. For the "moon in the sky" and "yes to myself" examples, if you include a space at the beginning it makes the right hash. 

That said, these IDs were simply meant to be a unique way to refer to a prompt, not necessarily regeneratable, and included for the very reason that the text could get garbled through an ML pipeline. For the sake of consistency, we will leave them as is.

I'll make a note of it in the documentation.

**Comment by mjpost** [comment]
The reason I encountered this (and the reason for you to maybe be concerned) is that your provided script [my_cands_extract.py](https://github.com/duolingo/duolingo-sharedtask-2020/blob/master/my_cands_extract.py) uses hashes of fairseq's outputting of its input. These hashes—and therefore the scoring via that script—fail for the reasons described above.

Of course, it's easy enough just for me to update the data files so that hashes will be correct.

**Comment by mayhewsw** [comment]
Ah, you're right. AFAIK, there's no way to pass IDs (as comments, for example) through the fairseq pipeline, so I resorted to this hack. A better way would be to associate finalized tokenized/processed text with IDs in some separate lookup file. 

I will update the base code to do this. Sorry for the inconvenience.

**Comment by mjpost** [comment]
Well, the hashing *does* work with a few small changes to the dataset. You've time-stamped it so it wouldn't be too hard to update it. Here's the diff if you like.

[diff.txt](https://github.com/duolingo/duolingo-sharedtask-2020/files/4135274/diff.txt)

**Comment by mjpost** [comment]
On the other hand, that's a fairseq-specific script. It would be more general to just require the prompts file to be passed as a separate argument, and assume the outputs are monotonic...

**Comment by mayhewsw** [comment]
That's a better idea, as long as fairseq is guaranteed to return every source sentence that goes in (e.g. no filtering by length, or by translation failure or something).

**Comment by mjpost** [comment]
"One line in, one line out" is a fundamental tenet of text processing. I think they do the right thing.

**Comment by mayhewsw** [comment]
The above pull-request should address this. 

As it turns out: fairseq-generate does not generate output in the order that it receives it, although it does retain the ordering in the metadata.
